### ISSUE TITLE
how to send video ?

### ISSUE THREAD

**Issue by hasanbasri1993** [open-wa/wa-automate-deploy-heroku#1]
is possible use this ??
https://github.com/heroku/heroku-buildpack-google-chrome

**Comment by smashah** [comment]
Yeah good spot @hasanbasri1993 . I'm sure I can switch out the buildpack. Will test out soon

**Comment by smashah** [comment]
@hasanbasri1993 I've now migrated to the chrome build pack as suggested. It is able to send video as expected. thanks
