### ISSUE TITLE
Heroku Env Variable setup when user logged in.

### ISSUE THREAD

**Issue by whatadeveloper22** [open-wa/wa-automate-deploy-heroku#4]
Can we change or add env variable when we scan qr on Heroku. For the same we need to remove the required from the app.json for the Heroku to launch app without login (if we have the session we can add on that time) and when yours logged in we can set the env variable from our session key and good to go.

**Comment by whatadeveloper22** [comment]
Any update here sir @smashah

**Comment by smashah** [comment]
@whatadeveloper22 The session data needs to be set via environment variable for heroku deployment
