### ISSUE TITLE
Update Deploy-Heroku to 4.8.2

### ISSUE THREAD

**Issue by silvaartur** [open-wa/wa-automate-deploy-heroku#48]
Update Deploy-Heroku to 4.8.2

**Comment by silvaartur** [comment]
Heroku force updating and not recognize session.data. Any ideas @smashah?

<img width="1250" alt="Captura de Tela 2021-07-12 às 15 50 49" src="https://user-images.githubusercontent.com/12688324/125340596-0612ed00-e329-11eb-8eb7-7023eeae9f37.png">

**Comment by smashah** [comment]
Updated to latest version. Heroku deployment working as expected now. thanks
